export const SET_NAME_GAME = 'SET_NAME_GAME';
export const SET_DATE_GAME = 'SET_DATE_GAME';
export const SET_TIME_GAME = 'SET_TIME_GAME';
export const SET_LINK_GOOGLE_GAME = 'SET_LINK_GOOGLE_GAME';
export const SET_LINK_IFRAME_GAME = 'SET_LINK_IFRAME_GAME';
